function wish() {
  const WishesArray = [
    "May all your dreams come true!",
    "Wishing you happiness, health, and success!",
    "May your day be filled with joy and laughter.",
    "Sending you positive vibes and good energy.",
    "May you find success in every endeavor.",
    "Wishing you a day filled with love and kindness.",
    "May your life be as colorful as a rainbow.",
    "May each moment bring you lasting memories.",
    "Sending warm wishes your way.",
    "May you be surrounded by love and positivity.",
    "Wishing you strength and courage to overcome any challenges.",
    "May your heart be full of gratitude and contentment.",
    "Sending good vibes for a fantastic day.",
    "May today be the start of a wonderful journey.",
    "Wishing you a day filled with love and laughter.",
    "May your path be lined with bright opportunities.",
    "Sending you sunshine and smiles.",
    "May your troubles be less and your blessings be more.",
    "Wishing you a day of joy and celebration.",
    "May your heart be light, your mind be fierce, and your spirit be free.",
    "Sending you positive thoughts for a successful day.",
    "May you be surrounded by love and laughter always.",
    "Wishing you the strength to face every challenge with a smile.",
    "May your dreams soar as high as your heart desires.",
    "Sending you good vibes and positive energy.",
    "May today be the best day of your life.",
    "Wishing you success in all your future endeavors.",
    "May your journey be filled with love and happiness.",
    "Sending you peace, love, and positive vibes.",
    "May your days be as bright as the sunniest day.",
    "Wishing you love, luck, and lots of laughter.",
    "May your heart be as light as a feather.",
    "Sending you good wishes for a bright and beautiful day.",
    "May you achieve all that you aspire for.",
    "Wishing you a day filled with beautiful moments.",
    "May you find joy in the little things.",
    "Sending you strength and positivity.",
    "May your heart be a magnet for miracles.",
    "Wishing you love, laughter, and all the happiness in the world.",
    "May your day be as sweet as honey.",
    "Sending you good vibes for a peaceful day.",
    "May your journey be filled with adventure and discovery.",
    "Wishing you a day filled with love and laughter.",
    "May your troubles be less and your blessings be more.",
    "Sending you sunshine and smiles.",
    "May your dreams come true and your worries be few.",
    "Wishing you success in all your endeavors.",
    "May your heart be light, your mind be fierce, and your spirit be free.",
    "Sending you positive thoughts for a bright and beautiful day.",
    "May your day be as bright as your smile.",
    "Wishing you love, luck, and lots of laughter.",
    "May your journey be filled with joy and excitement.",
    "Sending you peace, love, and positive energy.",
    "May your days be filled with sunshine and rainbows.",
    "Wishing you success in all your endeavors.",
    "May your heart be a magnet for miracles.",
    "Sending you good vibes for a wonderful day.",
    "May your dreams be bigger than your fears.",
    "Wishing you love, laughter, and all the happiness in the world.",
    "May your day be as sweet as chocolate.",
    "Sending you good vibes for a peaceful and relaxing day.",
    "May your journey be filled with love and kindness.",
    "Wishing you a day filled with joy and laughter.",
    "May your troubles be less and your blessings be more.",
    "Sending you sunshine and positive energy.",
    "May your dreams come true and your worries be few.",
    "Wishing you success and fulfillment in all your endeavors.",
    "May your heart be light, your mind be sharp, and your spirit be free.",
    "Sending you positive thoughts for a fantastic day.",
    "May your day be as bright as your smile.",
    "Wishing you love, luck, and lots of laughter.",
    "May your journey be filled with joy and adventure.",
    "Sending you peace, love, and positive vibes.",
    "May your days be filled with happiness and contentment.",
    "Wishing you success in all your future endeavors.",
    "May your heart be a magnet for all good things.",
    "Sending you good vibes for a wonderful day.",
    "May your dreams be bigger than your fears.",
    "Wishing you love, laughter, and boundless joy.",
    "May your day be as sweet as honey.",
    "Sending you good vibes for a peaceful and relaxing day.",
    "May your journey be filled with love and compassion.",
    "Wishing you a day filled with joy and laughter.",
    "May your troubles be less and your blessings be more.",
    "Sending you sunshine and positive energy.",
    "May your dreams come true and your worries be few.",
    "Wishing you success and fulfillment in all your endeavors.",
    "May your heart be light, your mind be sharp, and your spirit be free.",
    "Sending you positive thoughts for a fantastic day.",
    "May your day be as bright as your smile.",
    "Wishing you love, luck, and lots of laughter.",
    "May your journey be filled with joy and adventure.",
    "Sending you peace, love, and positive vibes.",
    "May your days be filled with happiness and contentment.",
    "Wishing you success in all your future endeavors.",
    "May your heart be a magnet for all good things.",
    "Sending you good vibes for a wonderful day.",
    "May your dreams be bigger than your fears.",
    "Wishing you love, laughter, and boundless joy.",
    "May your day be as sweet as honey.",
    "Sending you good vibes for a peaceful and relaxing day.",
    "May your journey be filled with love and compassion.",
    "Wishing you a day filled with joy and laughter.",
    "May your troubles be less and your blessings be more.",
    "Sending you sunshine and positive energy.",
    "May your dreams come true and your worries be few.",
    "Wishing you success and fulfillment in all your endeavors.",
    "May your heart be light, your mind be sharp, and your spirit be free.",
    "Sending you positive thoughts for a fantastic day.",
    "May your day be as bright as your smile.",
    "Wishing you love, luck, and lots of laughter.",
    "May your journey be filled with joy and adventure.",
    "Sending you peace, love, and positive vibes.",
    "May your days be filled with happiness and contentment.",
    "Wishing you success in all your future endeavors.",
    "May your heart be a magnet for all good things.",
    "Sending you good vibes for a wonderful day.",
    "May your dreams be bigger than your fears.",
    "Wishing you love, laughter, and boundless joy.",
  ];

  // Get a random wish from the array
  const randomIndex = Math.floor(Math.random() *  WishesArray.length);
  const message =  WishesArray[randomIndex];

  // Get the phone number input
  const phoneNumberInput = document.getElementById("go");
  let phoneNumber = phoneNumberInput.value;

  // Remove any non-digit characters from the phone number
  phoneNumber = '92' + phoneNumber.replace(/\D/g, '').replace(/^0+/, ''); 

  // Validate the phone number
  if (phoneNumber.length > 0 && !isNaN(phoneNumber)) {
    // Construct the WhatsApp link with the message
    const whatsappLink = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`;

    // Open the link in a new tab/window
    window.open(whatsappLink, '_blank');
  } else {
    alert("Error: Please enter a valid phone number (remove spaces and add country code).");
  }
}

